Repository dangphung4/Leaflet, pull requests merged in 2025-02, with the labels that each got.

#68 feat: calendar agenda improvements and UI changes
  notes/src/App.tsx
  notes/src/Core/Database/db.ts
  notes/src/Core/Pages/Calendar.tsx
  notes/src/Core/Pages/Folders.tsx
Labels: enhancement, Bug fix, Review effort [1-5]: 4

#71 fix: ui not working well on mobile in calendar edit/create page
  notes/src/Core/Pages/Calendar.tsx
Labels: enhancement, Bug fix

#70 ci: Update commitlintrc.json
  .github/commitlintrc.json
Labels: enhancement, Review effort [1-5]: 1

#73 ci: update commit lint yaml to exclude bots
  .commitlintrc.json
  notes/src/Core/Pages/Calendar.tsx
Labels: enhancement, Review effort [1-5]: 2

#75 ci: ignore penify
  .commitlintrc.json
  .github/workflows/commit-lint.yaml
Labels: enhancement, Review effort [1-5]: 2

#77 ci: update commitlintrc.json
  .github/commitlintrc.json
Labels: enhancement, Review effort [1-5]: 2

#78 ci: update commit-lint.yaml
  .github/workflows/commit-lint.yaml
Labels: enhancement, Review effort [1-5]: 2

#79 feat: user facing changes"
  notes/README.md
  notes/package-lock.json
  notes/package.json
  notes/src/App.tsx
  notes/src/Core/Components/Productivity/NewHabitDialog.tsx
  notes/src/Core/Components/Productivity/NewTaskDialog.tsx
  notes/src/Core/Components/ShareDialog.tsx
  notes/src/Core/Components/navbar.tsx
  notes/src/Core/Database/db.ts
  notes/src/Core/Pages/EditNote.tsx
  notes/src/Core/Pages/Folders.tsx
  notes/src/Core/Pages/Home.tsx
  notes/src/Core/Pages/Notes.tsx
  notes/src/Core/Pages/Productivity.tsx
  notes/src/components/ui/progress.tsx
  notes/src/components/ui/sidebar.tsx
  notes/src/components/ui/skeleton.tsx
  notes/src/hooks/use-mobile.tsx
Labels: documentation, enhancement, Review effort [1-5]: 4

#83 feat: import and export docx and google docs
  notes/package-lock.json
  notes/package.json
  notes/public/pdf.worker.min.mjs
  notes/src/App.tsx
  notes/src/Core/Auth/GoogleAuthProvider.tsx
  notes/src/Core/Components/ImportDialog.tsx
  notes/src/Core/Database/db.ts
  notes/src/Core/Pages/EditNote.tsx
  notes/src/Core/Pages/Notes.tsx
  notes/src/components/ui/spinner.tsx
  notes/vite.config.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 4

#90 Dang/reroute
  notes/vercel.json
Labels: enhancement, Review effort [1-5]: 2

#93 chore: update Editor.tsx css
  notes/src/Core/Components/Editor.tsx
Labels: enhancement, Review effort [1-5]: 1

#96 Revert "fix: update pdf export"
  notes/src/Core/Pages/EditNote.tsx
Labels: enhancement, Review effort [1-5]: 2

#101 feat: saas config new app name and logo
  README.md
  notes/README.md
  notes/globals.css
  notes/index.html
  notes/public/assets/leaflet-maskable.png
  notes/public/assets/leaflet-maskable.svg
  notes/public/manifest.json
  notes/scripts/copy-assets.js
  notes/src/Core/Components/Editor.tsx
  notes/src/Core/Database/db.ts
  notes/src/Core/Pages/Home.tsx
  notes/src/Core/Pages/Install.tsx
  notes/src/Core/Pages/Notes.tsx
  notes/src/Core/utils/noteUtils.ts
  notes/src/assets/leaflet-maskable.png
  notes/src/assets/leaflet-maskable.svg
  notes/src/service-worker.ts
  notes/src/styles/editor.css
  notes/vite.config.ts
Labels: documentation, enhancement
